# fly.toml file generated for ts-fly on 2023-03-29T22:40:02+08:00

app = "ts-fly"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin" # "hkg"

[env]
PORT = "41641"
# create a reusable or ephemeral auth key
# ephemeral auth key are not working for use as exit node as they are ipv6 only
# flyctl secrets set TAILSCALE_AUTH_KEY=tskey-...

[experimental]
auto_rollback = false
private_network = true

[[services]]
protocol = "udp"
internal_port = 8080

[[services.ports]]
port = "41641"
